### ISSUE TITLE
ImageMagick bugs and problems

### ISSUE THREAD

**Issue by Kaos-Industries** [adrianboston/srcset#2]
Hi there and thanks for a great tool, images served at different sizes for resolutions are so crucial for modern web dev, and I really didn't fancy writing my own Bash script to do the hard work, which is what led me to your script via Google. 

While researching the topic I also came across the [following SmashingMagazine article](https://www.smashingmagazine.com/2015/06/efficient-image-resizing-with-imagemagick/) which points out some problems with using ImageMagick for this sort of stuff, namely that it has bad defaults and can result in bad quality images. For obvious reasons this is worrying when weighing up an automated tool to let loose on your site's images. If you're aware of these issues with IM did you do anything to fix them in your script, or is there a reason you decided not?

I'd really appreciate an answer to help me make a decision for my workflow, and once again, thank you for the tool.

**Comment by adrianboston** [comment]
Hmm good article and exactly what i was thinking around the same time 5 years ago. Its strange many others havent figured this simple trick for their web server performance. 

Yes you can set the IMAGE QUALITY to whatever you like. The default is 100% which is far too high and doesn't compress JPGS enough. I found 95% to be fine. 75% is ok but does remove a lot of details. 

The problem with this script is that killing the process is difficult. Since each loop spawns another script. So I recently made the Rust tool. There is a OSX Binary for an early release. I can make another OSX binary for the current version

I only have OSX so that is all I can do. However, Rust is dead easy to install and use unlike C++.

**Comment by adrianboston** [comment]
It looks like there is a possible way to do image quality for jpeg.

https://docs.rs/image/0.23.14/image/codecs/jpeg/struct.JpegEncoder.html#method.new_with_quality

**Comment by adrianboston** [comment]
I will add that that article is really optimizing the cr&p out of one single image.  Imagemagick default applies no compression while photoshop and others might. So from that point of view yes Imagemagick fails to produce a smaller image -- FOR THE SAME DIMENSIONS.

The biggest gain by far is simply serving a file with a SMALLER DIMENSION that is suitable for the browser or devices width.

**Comment by adrianboston** [comment]
Be done soon with quality, sigma, thresh

**Comment by adrianboston** [comment]
Ok the v1.3.0 has a lot of new features including setting quality for jpeg images. Plus image unsharpen or blur as suggested by that article. And you can set your own image sizes for example. default is "480, 640, 768, 960, 1024, 1366, 1600, 1920"
